openapi: '3.0.3'
info:
  version: 1.0.0
  title: Jane test client
paths:
  /endpoint:
    get:
      summary: Simple endpoint
      operationId: getEndpoint
      responses:
        '200':
          description: Simple endpoint response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RootLevel'
components:
  schemas:
    RootLevel:
      type: object
      properties:
        subLevel-1:
          type: string
